version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: github.com/stretchr/testify
        versions:
          - 1.7.0
