name: Create Release
on:
  push:
    tags:
      - '*'

jobs:
  build_project_and_release:
    name: Build Project Executables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build simple parser
        run: go build -ldflags "-X main.readerType=simple" -o cs-round-parser-simple.exe

      - name: Build default parser
        run: go build -o cs-round-parser.exe

      - name: Create Release
        id: create_new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload simple parser executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_new_release.outputs.upload_url }}
          asset_path: ./cs-round-parser-simple.exe
          asset_name: cs-round-parser-simple.exe
          asset_content_type: application/octet-stream

      - name: Upload default parser executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_new_release.outputs.upload_url }}
          asset_path: ./cs-round-parser.exe
          asset_name: cs-round-parser.exe
          asset_content_type: application/octet-stream
